server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://yys.server1.com:1001/eureka/
#配置服务链追踪
#spring:
#  zipkin:
#    base-url: http://localhost:9411
#配置断路器
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: consumer1