server:
  port: 8000
  servlet:
    context-path: /sso
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8888/oauth/check_token
    client:
      client-id: server1
      client-secret: secret
      user-authorization-uri: http://localhost:8888/oauth/authorize
      access-token-uri: http://localhost:8888/oauth/token


