server:
#  servlet:
#    context-path: /sso
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: youyue.me.sso.server.entity
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloudauth?serverTimezone=Asia/Shanghai
#    username: root
#    password: root
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=Asia/Shanghai
    username: root
    password: yl199709234513y.
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      connection-timeout: 60000
      connection-test-query: SELECT 1
#    driver-class-name: com.mysql.cj.jdbc.Driver